(ns mapp.views.verifications-settings)

(def column-settings
  [[:id 50 nil]
   [:upload 25 nil]
   [:count 100 nil]
   [:counteragent 50 nil]
   [:ca_short_name 350 nil]
   [:conditions 50 nil]
   [:date 100 nil]
   [:verification_type 30 nil]
   [:interval 30 nil]
   [:protocol_number 50 nil]
   [:methodology_id 50 nil]
   [:met_short_name 100 nil]
   [:registry_number 100 nil]
   [:mi_type 250 nil]
   [:serial_number 150 nil]
   [:manufacture_year 75 nil]
   [:channels 50 nil]
   [:components 350 nil]
   [:scope 350 nil]
   [:area 30 nil]
   [:sw_name 100 nil]
   [:sw_version 100 nil]
   [:sw_version_real 100 nil]
   [:sw_checksum 100 nil]
   [:sw_algorithm 100 nil]
   ;[:voltage nil nil]
   ;[:other nil nil]
   ;[:sign_mi nil nil]
   ;[:sign_pass nil nil]
   [:protocol 100 nil]
   [:copy_from 100 nil]
   [:comment 300 nil]])

(def toolbar-fields-settings
  '(["id" " id "]
   ["выгрузка" " upload "]
   ["год" " manufacture_year "]
   ["дата" " date "]
   ["зав. №" " serial_number "]
   ["количество" " channels "]
   ["контрагент" " short_name "]
   ["объем" " scope "]
   ["протокол" " protocol_number "]
   ["рег. №" " registry_number "]
   ["состав" " components "]
   ["счет" " count "]
   ["тип СИ" " mi_type "]))

(def fields-settings
  '([:id "id" true]
    [:upload "Выгрузка" true]
    [:count "Счет" true]
    [:counteragent "id контрагента" true]
    [:ca_short_name "Контрагент" false]
    [:conditions "id условия поверки" true]
    [:date "Дата поверки" false]
    [:verification_type "Вид работ" true]
    [:interval "МПИ" true]
    [:protocol_number "Протокол №" true]
    [:methodology_id "id методики" true]
    [:registry_number "Регистрационный №" false]
    [:met_short_name "Методика поверки" false]
    [:mi_type "Наименование, тип, мод. СИ" true]
    [:serial_number "Заводской №" true]
    [:manufacture_year "Год выпуска" true]
    [:channels "Каналов" true]
    [:components "Состав" true]
    [:scope "Объем поверки" true]
    [:area "Сфера" true]
    [:sw_name "Наименование ПО" true]
    [:sw_version "Версия ПО (по НД)" true]
    [:sw_version_real "Версия ПО" true]
    [:sw_checksum "Контрольная сумма" true]
    [:sw_algorithm "Алгоритм" true]
    [:voltage "Напряжение" true]
    [:other "Прочие" true]
    [:sign_mi "Клеймо СИ" true]
    [:sign_pass "Клеймо паспорт" true]
    [:protocol "Протокол" true]
    [:comment "Комментарий" true]))
