(ns mapp.views.verifications-settings)

(def edit-panel-settings
  '([:id "id" true]
    [:upload "Выгрузка" true]
    [:count "Счет" true]
    [:counteragent "id контрагента" true]
    [:ca_short_name "Контрагент" false]
    [:conditions "id условия поверки" true]
    [:date "Дата" false]
    [:verification_type "Вид поверки" true]
    [:interval "МПИ" true]
    [:protocol_number "Протокол №" true]
    [:methodology_id "id методики" true]
    [:registry_number "Рег. №" false]
    [:mi_type "Тип СИ" true]
    [:serial_number "Зав. №" true]
    [:manufacture_year "Год выпуска" true]
    [:channels "Каналов" true]
    [:components "Состав" true]
    [:scope "Объем поверки" true]
    [:area "Сфера" true]
    [:sw_name "Наименование ПО" true]
    [:sw_version "Версия ПО (по НД)" true]
    [:sw_version_real "Версия ПО" true]
    [:sw_checksum "Контрольная сумма" true]
    [:sw_algorithm "Алгоритм" true]
    [:voltage "Напряжение" true]
    [:other "Прочие" true]
    [:sign_mi "Клеймо СИ" true]
    [:sign_pass "Клеймо паспорт" true]
    [:protocol "Протокол" true]
    [:comment "Комментарий" true]))
